### ISSUE TITLE
Null timestamp values cause invalid output in snapshotserver

### ISSUE THREAD

**Issue by kriswehner** [30x/transicator#18]
Having tried it with our data, we've noticed that the snapshotserver breaks when it hits a null datetime in postgres.

This looks like:
"deleted":{"value":"Invalid timestamp ","type":1184}

in the output. Ideally, I'd like to see this as "value": null but having dug into the pgclient I realize how tricky this is.

In a related question, would it make sense to maybe use a normal postgres driver for the snapshot server? It would side-step having to babysit a lot of these driver issues for this usecase, which is a lot more generic than the changeserver replication protocol.

**Comment by gbrail** [comment]
Right now the "lib/pq" driver doesn't let you select an isolation level, which I think is important in the snapshot case since we read a lot of tables using "repeatable read." We also use our own client right now to put the PG type OID in the snapshot output, although I don't think that we need that any more.

At any rate I'm looking at the NULL issues and they're not all in the driver, although some are.

Eventually, however, moving to a driver like lib/pq would be a good thing.

**Comment by kriswehner** [comment]
Have you looked at https://github.com/jackc/pgx ? It offers the transaction isolation level support and also advertises null datetime handling.

**Comment by gbrail** [comment]
null timestamps now return something more reasonable.

I might do some more work on timestamps and nulls in the future. However right now the output from snapshotserver seems reasonable, and our needs for a PG driver are actually fairly simple. For now I'm going to move on to other stuff.
