### ISSUE TITLE
If a client requests a change that is "too old", inform them they need to fetch a new snapshot

### ISSUE THREAD

**Issue by kriswehner** [30x/transicator#9]
One persistent problem we have is, for clients that are offline for long periods of time, they can & do request changes that are older than the available WAL we have stored on disk.

In this scenario, we need to inform the client that their database is too old and that they should request a new snapshot.

**Comment by gbrail** [comment]
Now that we have RocksDB in, a simple fix might be to have the storage module, when scanning a range, go back one record and see if there's anything there. If not, then it can return an extra parameter in each API response.

I have an idea how this might work, but probably won't get to it until early next week.

**Comment by gbrail** [comment]
"backing up" doesn't work because we don't know what to do if there have been no changes for a particular scope for a long time. I think that a better solution involves a new index of sequence numbers in order, so that at any point the response can include the lowest sequence number in the system.

That way, every API call returns the lowest sequence number that we have. If a client asked for changes since X, and the response that they get back says that the lowest sequence number in the DB is X-N, then they know that they missed changes and they need to get a new snapshot.

**Comment by kriswehner** [comment]
One thing we were discussing today that may be relevant: In order to be able to do efficient multi-scope scans, we think we need to reverse the database keys so they're:


version | lsn | scope

instead of

version | scope | lsn

This will let us, in mutli-scope cases, do an efficient scan of the database based on the LSN gap of the client and then filtering for scope in the golang code. If we do this, it will also enable the "backing up" scenario without having to have another index.

Multi-scope scans are a big usecase for us, so this is pretty high priority.

Thoughts?

**Comment by gbrail** [comment]
Sorry -- I think that you missed a part where you said "keys so they're:".

I think that we should take a few days (should be easy this week -- I will
be on line Thursday morning but then not for the rest of the weekend) and
see what some different persistence options are and do a few calculations
before we go too far.

For instance, in our case I expect thousands of individual scopes with
varying data rates so that some will change pretty often and others rarely.
But it'd be nice to avoid reading twice...

**Comment by kriswehner** [comment]
Nope, that was as intended, just apparently unclear. I'm suggesting reversing the key storage order so that it's LSN first, then scope.

The database nerd in me says: By and large most caught up clients (the common case) will be relatively close to the head of the master's max LSN, usually a few hours behind at most. If the tree is stored in LSN order, this will let the caching of the current entries in the index be very effective. If it's in scope order, the access pattern is going to be close to pure random, which is going to make any attempt at caching ineffective.

**Comment by gbrail** [comment]
Yes -- I just want to do an experiment. Having LSN first (which I had once
before) is simpler to code and will likely work well. I'd like to write a
little benchmark to satisfy myself and we need one anyway.

Keep in mind the bootstrap case, in which the client has a snapshot but
does not know the sequence number (because we don't know how to
consistently get that out of PG and put it in the snapshot). In that case,
the client makes an API call with no "since" parameter, but a "snapshot"
parameter. In the change server we read everything from the beginning, and
filter out anything that was in the snapshot. At that point, the client has
a "last sequence" value, and the client can again use that value for
retrieving the next set of changes.

**Comment by gbrail** [comment]
Anyway, how should the API work? Here's one proposal:

First, for every call to /changes we return three things: the change list
(may be empty), the highest sequence in the DB, and the lowest.

Imagine that the DB contains the following changes (I'll just use numbers
to represent the sequence):

3
4
5
6

client calls would work as follows:

GET /changes?since=3
  Changes 4, 5, and 6, first=3, last=6

GET /changes?since=5
  first=3 ,last=6, empty list

GET /changes?since=1
  ERROR: Snapshot too old

**Comment by kriswehner** [comment]
That's what I had in mind yeah. 

Truth, in our system today, we only do the last one (snapshot too old) to avoid the overhead of the lookup. We also maintain a cached copy of the lowest LSN we have in memory that we update periodically to avoid the performance hit of re-querying it over and over. 

I'm not sure if the performance characteristics of rocksdb or the by-definition sharded nature of the data storage maxes that not a concern anymore. I could easily see it not being an issue.

**Comment by gbrail** [comment]
This is closed --

if the "since" parameter to changeserver represents a change that is older than the oldest change in the database, then the change server will return a 400 with a "SNAPSHOT_TOO_OLD" error instead of any changes. The client should then fetch a new snapshot.

**Comment by gbrail** [comment]
Jumped the gun on closing this -- PR coming.
